export interface TerminalLine {
  type: 'command' | 'output' | 'error' | 'success' | 'info' | 'credential' | 'warning'
  text: string
  delay: number
}

export interface TerminalSession {
  id: string
  mode: string
  icon: string
  status: 'running' | 'completed' | 'idle'
  command: string
  lines: TerminalLine[]
  color: string
}

export const TERMINAL_SESSIONS: TerminalSession[] = [
  {
    id: 'migrating',
    mode: 'MIGRATING',
    icon: '🔄',
    status: 'running',
    command: 'macrocoder migrate --from express --to axum',
    color: '#3b82f6',
    lines: [
      { type: 'command', text: '$ macrocoder migrate --from express --to axum', delay: 0 },
      { type: 'info', text: '[macrocoder] Initializing migration engine...', delay: 400 },
      { type: 'info', text: '[macrocoder] Source: Express.js (Node.js)', delay: 300 },
      { type: 'info', text: '[macrocoder] Target: Axum (Rust)', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Analyzing route definitions...', delay: 600 },
      { type: 'success', text: '✓ Found 14 route handlers in src/routes/', delay: 800 },
      { type: 'success', text: '✓ Found 8 middleware functions', delay: 400 },
      { type: 'success', text: '✓ Found 3 WebSocket endpoints', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Generating Rust project structure...', delay: 1000 },
      { type: 'output', text: '  Creating Cargo.toml with axum, tokio, serde...', delay: 600 },
      { type: 'output', text: '  Creating src/main.rs with Router setup...', delay: 400 },
      { type: 'output', text: '  Creating src/handlers/mod.rs...', delay: 300 },
      { type: 'output', text: '  Creating src/handlers/users.rs...', delay: 200 },
      { type: 'output', text: '  Creating src/handlers/auth.rs...', delay: 200 },
      { type: 'output', text: '  Creating src/handlers/api.rs...', delay: 200 },
      { type: 'output', text: '  Creating src/middleware/mod.rs...', delay: 200 },
      { type: 'output', text: '  Creating src/models/user.rs...', delay: 200 },
      { type: 'output', text: '  Creating src/models/session.rs...', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Converting middleware chain...', delay: 800 },
      { type: 'success', text: '✓ auth_middleware → AuthLayer (tower)', delay: 600 },
      { type: 'success', text: '✓ rate_limiter → RateLimitLayer', delay: 400 },
      { type: 'success', text: '✓ cors_handler → CorsLayer::new()', delay: 300 },
      { type: 'success', text: '✓ error_handler → IntoResponse impl', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Translating route handlers...', delay: 1200 },
      { type: 'output', text: '  GET  /api/users          → handlers::users::list', delay: 400 },
      { type: 'output', text: '  POST /api/users          → handlers::users::create', delay: 300 },
      { type: 'output', text: '  GET  /api/users/:id      → handlers::users::get', delay: 300 },
      { type: 'output', text: '  PUT  /api/users/:id      → handlers::users::update', delay: 300 },
      { type: 'output', text: '  DELETE /api/users/:id    → handlers::users::delete', delay: 300 },
      { type: 'output', text: '  POST /api/auth/login     → handlers::auth::login', delay: 300 },
      { type: 'output', text: '  POST /api/auth/register  → handlers::auth::register', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Converting async handlers to Rust...', delay: 1000 },
      { type: 'success', text: '✓ 14/14 handlers migrated', delay: 2000 },
      { type: 'success', text: '✓ Type-safe JSON serialization (serde)', delay: 400 },
      { type: 'success', text: '✓ Database pool configured (sqlx)', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Running cargo build...', delay: 800 },
      { type: 'output', text: '   Compiling macrocoder-migration v0.1.0', delay: 1500 },
      { type: 'output', text: '   Compiling axum v0.7.5', delay: 800 },
      { type: 'output', text: '   Compiling tokio v1.36.0', delay: 600 },
      { type: 'success', text: '    Finished dev [unoptimized + debuginfo] target(s)', delay: 2000 },
      { type: 'output', text: '', delay: 200 },
      { type: 'success', text: '✓ Migration complete: 14 routes, 8 middleware, 3 WS endpoints', delay: 400 },
      { type: 'info', text: '  Performance improvement: ~12x throughput, ~5x memory reduction', delay: 400 },
      { type: 'info', text: '  Next: Run `macrocoder test --suite migration` to verify', delay: 300 },
    ],
  },
  {
    id: 'analyzing',
    mode: 'ANALYZING',
    icon: '🔍',
    status: 'running',
    command: 'macrocoder analyze --repo github/acme/api-server',
    color: '#a855f7',
    lines: [
      { type: 'command', text: '$ macrocoder analyze --repo github/acme/api-server', delay: 0 },
      { type: 'info', text: '[macrocoder] Cloning repository...', delay: 500 },
      { type: 'output', text: 'Cloning into \'/tmp/mc-analysis/acme-api-server\'...', delay: 800 },
      { type: 'success', text: '✓ Repository cloned (247 files, 18,432 LOC)', delay: 1200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Running static analysis...', delay: 600 },
      { type: 'info', text: '[1/5] Architecture analysis...', delay: 400 },
      { type: 'output', text: '  Layers detected: API → Service → Repository → DB', delay: 600 },
      { type: 'success', text: '  ✓ Clean architecture pattern', delay: 300 },
      { type: 'warning', text: '  ⚠ Circular dependency: UserService ↔ AuthService', delay: 400 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[2/5] Security audit...', delay: 400 },
      { type: 'error', text: '  ✗ SQL injection risk in UserRepository:findById()', delay: 800 },
      { type: 'error', text: '  ✗ Hardcoded API key in config/production.js:14', delay: 400 },
      { type: 'warning', text: '  ⚠ JWT secret too short (16 chars, recommend 32+)', delay: 300 },
      { type: 'warning', text: '  ⚠ No rate limiting on /api/auth/login', delay: 300 },
      { type: 'success', text: '  ✓ CSRF protection configured', delay: 200 },
      { type: 'success', text: '  ✓ Password hashing: bcrypt (cost 12)', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[3/5] Performance profiling...', delay: 400 },
      { type: 'warning', text: '  ⚠ N+1 query in GET /api/users (missing eager load)', delay: 800 },
      { type: 'warning', text: '  ⚠ No database connection pooling configured', delay: 400 },
      { type: 'success', text: '  ✓ Response caching on /api/products', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[4/5] Test coverage analysis...', delay: 400 },
      { type: 'output', text: '  Overall coverage: 67.3%', delay: 600 },
      { type: 'warning', text: '  ⚠ handlers/auth.test.js: 23% coverage', delay: 400 },
      { type: 'warning', text: '  ⚠ services/payment.js: 0% coverage', delay: 300 },
      { type: 'success', text: '  ✓ models/user.test.js: 94% coverage', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[5/5] Dependency audit...', delay: 400 },
      { type: 'warning', text: '  ⚠ 3 outdated major versions (express 4.18→5.0)', delay: 600 },
      { type: 'error', text: '  ✗ 1 known vulnerability: lodash < 4.17.21', delay: 400 },
      { type: 'success', text: '  ✓ No unused dependencies detected', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'success', text: '═══════════════════════════════════════════', delay: 400 },
      { type: 'success', text: '  Analysis Complete', delay: 200 },
      { type: 'success', text: '  Score: 72/100 — Good, with actionable fixes', delay: 300 },
      { type: 'success', text: '═══════════════════════════════════════════', delay: 200 },
      { type: 'info', text: '  Critical: 3 | Warnings: 7 | Passed: 12', delay: 300 },
      { type: 'info', text: '  Run `macrocoder fix --repo acme/api-server --auto`', delay: 300 },
    ],
  },
  {
    id: 'fixing',
    mode: 'FIXING',
    icon: '🔧',
    status: 'running',
    command: 'macrocoder fix --auto --test',
    color: '#22c55e',
    lines: [
      { type: 'command', text: '$ macrocoder fix --auto --test', delay: 0 },
      { type: 'info', text: '[macrocoder] Auto-fix mode enabled', delay: 400 },
      { type: 'info', text: '[macrocoder] Test verification: ON', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Scanning for fixable issues...', delay: 600 },
      { type: 'success', text: '✓ Found 14 fixable issues across 8 files', delay: 800 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: '[1/14] Fixing SQL injection in UserRepository...', delay: 500 },
      { type: 'output', text: '  Before: db.query(`SELECT * FROM users WHERE id=${id}`)', delay: 400 },
      { type: 'output', text: '  After:  db.query(\'SELECT * FROM users WHERE id=$1\', [id])', delay: 300 },
      { type: 'success', text: '  ✓ Fixed — parameterized query', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: '[2/14] Removing hardcoded API key...', delay: 400 },
      { type: 'output', text: '  Before: const API_KEY = "sk-proj-xxxx...";', delay: 300 },
      { type: 'output', text: '  After:  const API_KEY = process.env.OPENAI_API_KEY;', delay: 300 },
      { type: 'output', text: '  Added:  .env.example with placeholder', delay: 200 },
      { type: 'success', text: '  ✓ Fixed — moved to environment variable', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: '[3/14] Fixing N+1 query in user list...', delay: 400 },
      { type: 'output', text: '  Before: users.map(u => db.query(\'SELECT * FROM posts...\'))', delay: 400 },
      { type: 'output', text: '  After:  db.query(\'SELECT * FROM posts WHERE user_id = ANY($1)\')', delay: 300 },
      { type: 'success', text: '  ✓ Fixed — batch query with ANY()', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: '[4/14] Adding rate limiter to /api/auth/login...', delay: 400 },
      { type: 'output', text: '  Added: express-rate-limit middleware', delay: 300 },
      { type: 'output', text: '  Config: 100 requests/15min per IP', delay: 200 },
      { type: 'success', text: '  ✓ Fixed — rate limiting enabled', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: '[5-14] Applying remaining fixes...', delay: 600 },
      { type: 'success', text: '  ✓ Updated lodash to 4.17.21', delay: 400 },
      { type: 'success', text: '  ✓ Added connection pooling (max: 20)', delay: 300 },
      { type: 'success', text: '  ✓ Fixed circular dependency (extracted TokenService)', delay: 300 },
      { type: 'success', text: '  ✓ Generated JWT secret (64 chars)', delay: 200 },
      { type: 'success', text: '  ✓ Added input validation to 6 endpoints', delay: 200 },
      { type: 'success', text: '  ✓ Fixed 3 TypeScript strict mode errors', delay: 200 },
      { type: 'success', text: '  ✓ Added missing error boundaries', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Running test suite...', delay: 800 },
      { type: 'output', text: '  PASS  src/models/user.test.js (12 tests)', delay: 600 },
      { type: 'output', text: '  PASS  src/handlers/auth.test.js (8 tests)', delay: 400 },
      { type: 'output', text: '  PASS  src/services/payment.test.js (5 tests)', delay: 400 },
      { type: 'output', text: '  PASS  src/middleware/rateLimit.test.js (3 tests)', delay: 300 },
      { type: 'success', text: '', delay: 200 },
      { type: 'success', text: 'Tests:       28 passed, 28 total', delay: 400 },
      { type: 'success', text: 'Coverage:    89.2% (was 67.3%)', delay: 300 },
      { type: 'success', text: 'Time:        4.2s', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'success', text: '✓ All 14 issues fixed. Tests passing.', delay: 400 },
    ],
  },
  {
    id: 'deploying',
    mode: 'DEPLOYING',
    icon: '🚀',
    status: 'running',
    command: 'macrocoder deploy --target hetzner',
    color: '#f97316',
    lines: [
      { type: 'command', text: '$ macrocoder deploy --target hetzner', delay: 0 },
      { type: 'info', text: '[macrocoder] Deploying to Hetzner Cloud...', delay: 400 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Building production image...', delay: 600 },
      { type: 'output', text: '  Step 1/12: FROM rust:1.75-slim AS builder', delay: 400 },
      { type: 'output', text: '  Step 2/12: WORKDIR /app', delay: 200 },
      { type: 'output', text: '  Step 3/12: COPY Cargo.toml Cargo.lock ./', delay: 200 },
      { type: 'output', text: '  Step 4/12: RUN cargo build --release', delay: 1000 },
      { type: 'output', text: '  Step 5/12: FROM debian:bookworm-slim', delay: 300 },
      { type: 'output', text: '  Step 6/12: COPY --from=builder /app/target/release/app /app', delay: 200 },
      { type: 'success', text: '  ✓ Image built: macrocoder-app:latest (24.3 MB)', delay: 800 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Provisioning infrastructure...', delay: 600 },
      { type: 'output', text: '  Creating server: macrocoder-prod-01 (CPX21)', delay: 800 },
      { type: 'output', text: '  Location: fsn1 (Falkenstein, DE)', delay: 300 },
      { type: 'output', text: '  OS: Ubuntu 22.04 LTS', delay: 200 },
      { type: 'success', text: '  ✓ Server created: 188.40.xx.xx', delay: 1200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Configuring infrastructure...', delay: 400 },
      { type: 'output', text: '  Setting up firewall rules...', delay: 400 },
      { type: 'output', text: '    ALLOW  22/tcp    (SSH)', delay: 200 },
      { type: 'output', text: '    ALLOW  80/tcp    (HTTP)', delay: 200 },
      { type: 'output', text: '    ALLOW  443/tcp   (HTTPS)', delay: 200 },
      { type: 'output', text: '    DENY   ALL OTHER', delay: 200 },
      { type: 'success', text: '  ✓ Firewall configured', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Deploying application...', delay: 600 },
      { type: 'output', text: '  Pushing image to registry...', delay: 800 },
      { type: 'output', text: '  Pulling image on server...', delay: 600 },
      { type: 'output', text: '  Starting container...', delay: 400 },
      { type: 'success', text: '  ✓ Container running (PID 1847)', delay: 600 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Setting up TLS...', delay: 400 },
      { type: 'output', text: '  Requesting Let\'s Encrypt certificate...', delay: 1000 },
      { type: 'success', text: '  ✓ Certificate issued for api.macrocoder.dev', delay: 800 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Running health checks...', delay: 400 },
      { type: 'output', text: '  GET /health → 200 OK (12ms)', delay: 400 },
      { type: 'output', text: '  GET /api/v1/status → 200 OK (8ms)', delay: 300 },
      { type: 'output', text: '  WebSocket /ws → Connected', delay: 300 },
      { type: 'success', text: '  ✓ All health checks passing', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'success', text: '═══════════════════════════════════════════', delay: 300 },
      { type: 'success', text: '  Deployment Complete', delay: 200 },
      { type: 'success', text: '  URL: https://api.macrocoder.dev', delay: 200 },
      { type: 'success', text: '  TLS: Let\'s Encrypt (expires 2026-07-02)', delay: 200 },
      { type: 'success', text: '═══════════════════════════════════════════', delay: 200 },
    ],
  },
  {
    id: 'securing',
    mode: 'SECURING',
    icon: '🛡️',
    status: 'running',
    command: 'macrocoder audit --fix --strict',
    color: '#ef4444',
    lines: [
      { type: 'command', text: '$ macrocoder audit --fix --strict', delay: 0 },
      { type: 'info', text: '[macrocoder] Security audit (strict mode)', delay: 400 },
      { type: 'info', text: '[macrocoder] Auto-fix: ENABLED', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Scanning codebase for vulnerabilities...', delay: 600 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[CRITICAL] SQL Injection — src/repos/user.ts:42', delay: 800 },
      { type: 'output', text: '  Template literal in SQL query detected', delay: 300 },
      { type: 'output', text: '  Severity: HIGH | CVSS: 9.8', delay: 200 },
      { type: 'success', text: '  → Fixed: Replaced with parameterized query', delay: 400 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[CRITICAL] Hardcoded Secret — config/prod.env:14', delay: 600 },
      { type: 'output', text: '  API key found in source code', delay: 200 },
      { type: 'output', text: '  Key: sk-proj-███████████████████████████████', delay: 300 },
      { type: 'success', text: '  → Fixed: Moved to environment variable', delay: 300 },
      { type: 'success', text: '  → Added to .gitignore', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[HIGH] XSS Vulnerability — src/views/profile.ejs:8', delay: 600 },
      { type: 'output', text: '  Unescaped user input in template', delay: 200 },
      { type: 'output', text: '  <%= user.bio %> should be <%- escape(user.bio) %>', delay: 300 },
      { type: 'success', text: '  → Fixed: Applied HTML escaping', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[HIGH] Insecure Cookie — src/middleware/session.ts:23', delay: 500 },
      { type: 'output', text: '  Cookie missing httpOnly and secure flags', delay: 300 },
      { type: 'success', text: '  → Fixed: Added httpOnly, secure, sameSite=strict', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[MEDIUM] Missing CSP Header', delay: 400 },
      { type: 'success', text: '  → Fixed: Added Content-Security-Policy header', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[MEDIUM] Dependency Vulnerability — lodash@4.17.20', delay: 400 },
      { type: 'output', text: '  Prototype Pollution (CVE-2021-23337)', delay: 300 },
      { type: 'success', text: '  → Fixed: Updated to lodash@4.17.21', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'info', text: '[LOW] Verbose Error Messages in Production', delay: 400 },
      { type: 'success', text: '  → Fixed: Generic error responses enabled', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'success', text: '═══════════════════════════════════════════', delay: 300 },
      { type: 'success', text: '  Security Audit Complete', delay: 200 },
      { type: 'success', text: '  7 vulnerabilities found, 7 fixed', delay: 200 },
      { type: 'success', text: '  Security Score: 42/100 → 96/100', delay: 200 },
      { type: 'success', text: '═══════════════════════════════════════════', delay: 200 },
    ],
  },
  {
    id: 'building',
    mode: 'BUILDING',
    icon: '⚡',
    status: 'running',
    command: 'macrocoder build --spec "API Gateway"',
    color: '#eab308',
    lines: [
      { type: 'command', text: '$ macrocoder build --spec "API Gateway"', delay: 0 },
      { type: 'info', text: '[macrocoder] Building: API Gateway Service', delay: 400 },
      { type: 'info', text: '[macrocoder] Spec: REST + WebSocket + gRPC', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Parsing specification...', delay: 600 },
      { type: 'success', text: '✓ 12 endpoints defined', delay: 400 },
      { type: 'success', text: '✓ 3 WebSocket channels', delay: 200 },
      { type: 'success', text: '✓ 2 gRPC services', delay: 200 },
      { type: 'success', text: '✓ Auth: JWT + API Key', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Generating project scaffold...', delay: 600 },
      { type: 'output', text: '  src/', delay: 100 },
      { type: 'output', text: '  ├── main.rs              (Axum server entry)', delay: 100 },
      { type: 'output', text: '  ├── config.rs            (Settings, env parsing)', delay: 100 },
      { type: 'output', text: '  ├── routes/', delay: 100 },
      { type: 'output', text: '  │   ├── mod.rs', delay: 100 },
      { type: 'output', text: '  │   ├── health.rs        (GET /health)', delay: 100 },
      { type: 'output', text: '  │   ├── users.rs         (CRUD operations)', delay: 100 },
      { type: 'output', text: '  │   └── auth.rs          (Login, register, refresh)', delay: 100 },
      { type: 'output', text: '  ├── services/', delay: 100 },
      { type: 'output', text: '  │   ├── mod.rs', delay: 100 },
      { type: 'output', text: '  │   ├── user_service.rs', delay: 100 },
      { type: 'output', text: '  │   └── auth_service.rs', delay: 100 },
      { type: 'output', text: '  ├── models/', delay: 100 },
      { type: 'output', text: '  │   ├── mod.rs', delay: 100 },
      { type: 'output', text: '  │   ├── user.rs', delay: 100 },
      { type: 'output', text: '  │   └── token.rs', delay: 100 },
      { type: 'output', text: '  ├── middleware/', delay: 100 },
      { type: 'output', text: '  │   ├── mod.rs', delay: 100 },
      { type: 'output', text: '  │   ├── auth.rs          (JWT validation)', delay: 100 },
      { type: 'output', text: '  │   └── rate_limit.rs    (Token bucket)', delay: 100 },
      { type: 'output', text: '  └── ws/', delay: 100 },
      { type: 'output', text: '      ├── mod.rs', delay: 100 },
      { type: 'output', text: '      └── handler.rs       (WebSocket upgrade)', delay: 100 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Implementing business logic...', delay: 800 },
      { type: 'success', text: '✓ User CRUD with pagination (offset + cursor)', delay: 600 },
      { type: 'success', text: '✓ JWT auth flow (access + refresh tokens)', delay: 400 },
      { type: 'success', text: '✓ Rate limiting (token bucket, 100 req/min)', delay: 300 },
      { type: 'success', text: '✓ WebSocket handler with room support', delay: 300 },
      { type: 'success', text: '✓ gRPC service stubs generated (tonic)', delay: 200 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Compiling...', delay: 600 },
      { type: 'output', text: '   Compiling api-gateway v0.1.0', delay: 1000 },
      { type: 'output', text: '   Compiling axum v0.7.5', delay: 600 },
      { type: 'output', text: '   Compiling tokio v1.36.0', delay: 400 },
      { type: 'output', text: '   Compiling sqlx v0.7.3', delay: 400 },
      { type: 'output', text: '   Compiling tonic v0.11.0', delay: 300 },
      { type: 'success', text: '    Finished release [optimized] target(s) in 18.4s', delay: 2000 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Running integration tests...', delay: 600 },
      { type: 'output', text: '  test health_check ... ok', delay: 300 },
      { type: 'output', text: '  test user_create_read_update ... ok', delay: 300 },
      { type: 'output', text: '  test user_delete ... ok', delay: 200 },
      { type: 'output', text: '  test auth_login_refresh ... ok', delay: 300 },
      { type: 'output', text: '  test auth_invalid_token_rejected ... ok', delay: 200 },
      { type: 'output', text: '  test rate_limit_enforced ... ok', delay: 300 },
      { type: 'output', text: '  test websocket_connect ... ok', delay: 300 },
      { type: 'output', text: '  test grpc_health_check ... ok', delay: 200 },
      { type: 'success', text: '', delay: 200 },
      { type: 'success', text: 'test result: ok. 8 passed; 0 failed; 0 ignored', delay: 400 },
      { type: 'success', text: 'Binary size: 12.4 MB (release, stripped)', delay: 300 },
      { type: 'success', text: '', delay: 200 },
      { type: 'success', text: '✓ Build complete. Ready for deployment.', delay: 400 },
    ],
  },
]

export const ACTIVITY_LOG = [
  { time: '14:30:00', event: 'Agent initialized', detail: 'MacroCoder v2.1.0 loaded', status: 'done' },
  { time: '14:30:15', event: 'Config loaded', detail: '6 modes enabled', status: 'done' },
  { time: '14:30:45', event: 'Connection pool ready', detail: 'PostgreSQL (max: 20)', status: 'done' },
  { time: '14:31:00', event: 'Cache warmed', detail: 'Redis: 847 keys loaded', status: 'done' },
  { time: '14:31:30', event: 'SSH tunnel established', detail: 'Hetzner → local dev', status: 'done' },
  { time: '14:32:01', event: 'Migration started', detail: 'Express.js → Axum', status: 'running' },
  { time: '14:32:15', event: 'Route analysis complete', detail: '14 handlers found', status: 'done' },
  { time: '14:32:45', event: 'Middleware mapped', detail: '8 → 8 tower layers', status: 'done' },
  { time: '14:33:00', event: 'Type generation', detail: 'serde derive macros applied', status: 'done' },
  { time: '14:33:42', event: 'Analysis started', detail: 'github/acme/api-server', status: 'running' },
  { time: '14:34:08', event: 'Auto-fix started', detail: '14 issues detected', status: 'running' },
  { time: '14:34:22', event: 'SQL injection fixed', detail: 'Parameterized query applied', status: 'done' },
  { time: '14:34:35', event: 'API key rotated', detail: 'Moved to env variable', status: 'done' },
  { time: '14:34:55', event: 'Deployment started', detail: 'Hetzner Cloud (fsn1)', status: 'running' },
  { time: '14:35:12', event: 'Security audit started', detail: 'Strict mode enabled', status: 'running' },
  { time: '14:35:30', event: 'Build started', detail: 'API Gateway spec', status: 'running' },
  { time: '14:35:45', event: 'Docker image built', detail: '24.3 MB (multi-stage)', status: 'done' },
  { time: '14:36:01', event: 'Migration compiled', detail: 'cargo build success', status: 'done' },
  { time: '14:36:15', event: 'Analysis complete', detail: 'Score: 72/100', status: 'done' },
  { time: '14:36:30', event: 'N+1 query fixed', detail: 'Batch query with ANY()', status: 'done' },
  { time: '14:36:44', event: 'Fixes applied', detail: '14/14 fixed, tests pass', status: 'done' },
  { time: '14:37:02', event: 'TLS provisioned', detail: 'Let\'s Encrypt cert issued', status: 'done' },
  { time: '14:37:18', event: 'Security score improved', detail: '42 → 96/100', status: 'done' },
  { time: '14:37:30', event: 'Rate limiter added', detail: '100 req/min per IP', status: 'done' },
  { time: '14:37:45', event: 'Build complete', detail: '8 tests passing', status: 'done' },
  { time: '14:38:00', event: 'Deployment live', detail: 'api.macrocoder.dev', status: 'done' },
  { time: '14:38:15', event: 'Health check passed', detail: '200 OK (12ms)', status: 'done' },
  { time: '14:38:30', event: 'WebSocket connected', detail: '/ws → active', status: 'done' },
  { time: '14:38:45', event: 'gRPC service ready', detail: 'HealthCheck OK', status: 'done' },
  { time: '14:39:00', event: 'All systems verified', detail: '6/6 modes operational', status: 'done' },
]

export const LIVE_STATS = {
  uptime: '99.97%',
  responseTime: '12ms',
  deployments: 147,
  filesChanged: 2847,
  testsPassing: '100%',
  migrations: 23,
  securityScore: '96/100',
  activeAgents: 6,
}
