export interface TerminalLine {
  type: 'command' | 'output' | 'error' | 'success' | 'info' | 'credential' | 'warning' | 'censored'
  text: string
  delay: number
}

export interface TerminalSession {
  id: string
  mode: string
  icon: string
  status: 'running' | 'completed' | 'idle'
  command: string
  lines: TerminalLine[]
  color: string
  description: string
}

export interface JournalEntry {
  id: string
  day: number
  time: string
  title: string
  body: string
  expandedThought: string
}

export const TERMINAL_SESSIONS: TerminalSession[] = [
  {
    id: 'deploying',
    mode: 'DEPLOY',
    icon: '▲',
    status: 'running',
    command: 'macrocoder deploy --env production --region eu-w...',
    color: '#f97316',
    description: 'Zero-downtime production deployment',
    lines: [
      { type: 'command', text: '$ macrocoder deploy --env production --region eu-west', delay: 0 },
      { type: 'output', text: '', delay: 200 },
      { type: 'output', text: '◎ Authenticating...', delay: 400 },
      { type: 'credential', text: 'Token: sk-proj-8a3f2b1c9e4d7f6a0b5c8d1e2f3a4b5c6d7e8f', delay: 600 },
      { type: 'success', text: '✓ Authenticated as team@pullport.com', delay: 500 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '» Building production bundle...', delay: 600 },
      { type: 'success', text: '├── Compiling 847 modules', delay: 800 },
      { type: 'success', text: '├── Tree-shaking unused exports', delay: 400 },
      { type: 'success', text: '├── Minifying... 2.4MB → 412KB', delay: 500 },
      { type: 'success', text: '└── Generating source maps', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Provisioning infrastructure...', delay: 600 },
      { type: 'credential', text: 'Database: postgresql://██████████████@db.████.supabase.co:5432', delay: 500 },
      { type: 'credential', text: 'Storage: s3://████████-prod-assets', delay: 300 },
      { type: 'info', text: 'CDN: https://cdn.████████.app', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Running migrations...', delay: 500 },
      { type: 'success', text: '+ ALTER TABLE users ADD COLUMN avatar_url TEXT;', delay: 400 },
      { type: 'success', text: '+ CREATE INDEX idx_users_email ON users(email);', delay: 300 },
      { type: 'success', text: '✓ 2 migrations applied', delay: 400 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Health checks...', delay: 400 },
      { type: 'success', text: 'API ✓ 12ms', delay: 500 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: '$ docker push registry.macrocoder.dev/app:2.4.1', delay: 600 },
      { type: 'output', text: 'Pushing layer 1/5... done', delay: 400 },
      { type: 'output', text: 'Pushing layer 2/5... done', delay: 300 },
      { type: 'output', text: 'Pushing layer 3/5... done', delay: 300 },
      { type: 'success', text: '✓ Image pushed successfully', delay: 400 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: '$ kubectl rollout status deployment/app', delay: 500 },
      { type: 'success', text: 'deployment "app" successfully rolled out', delay: 800 },
      { type: 'output', text: '', delay: 300 },
      { type: 'success', text: '✓ v2.4.1 is live at https://app.macrocoder.dev', delay: 400 },
    ],
  },
  {
    id: 'debugging',
    mode: 'DEBUG',
    icon: '›',
    status: 'running',
    command: 'macrocoder diagnose --trace',
    color: '#f97316',
    description: 'Incident response resolved in 47 seconds',
    lines: [
      { type: 'command', text: '$ macrocoder diagnose --trace', delay: 0 },
      { type: 'output', text: '', delay: 300 },
      { type: 'warning', text: '⚠ INCIDENT DETECTED — 500 errors spiking', delay: 800 },
      { type: 'output', text: '', delay: 400 },
      { type: 'output', text: '◎ Correlating error logs with recent deploys...', delay: 600 },
      { type: 'info', text: '[Claude Code] Analyzing stack traces from last 5m', delay: 500 },
      { type: 'output', text: '  Found 342 errors in /api/v1/checkout', delay: 400 },
      { type: 'output', text: '  Root cause: FastAPI dependency injection failure', delay: 400 },
      { type: 'output', text: '', delay: 300 },
      { type: 'info', text: '[Claude Code] Reading src/api/routes/checkout.py', delay: 500 },
      { type: 'error', text: '  ✗ Line 47: async def checkout(db: Session = Depends(get_db))', delay: 400 },
      { type: 'error', text: '    TypeError: get_db() missing required kwarg "pool_size"', delay: 400 },
      { type: 'output', text: '', delay: 300 },
      { type: 'info', text: '[Claude Code] Checking git blame...', delay: 400 },
      { type: 'output', text: '  Introduced in commit a3f8b2c (12 min ago)', delay: 300 },
      { type: 'output', text: '  Author: deploy-bot — refactored DB pool config', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Generating fix...', delay: 500 },
      { type: 'output', text: '  - def get_db():', delay: 200 },
      { type: 'success', text: '  + def get_db(pool_size: int = 20):', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Running tests...', delay: 400 },
      { type: 'output', text: '  PASS  tests/test_checkout.py (7 tests)', delay: 500 },
      { type: 'output', text: '  PASS  tests/test_db_pool.py (4 tests)', delay: 300 },
      { type: 'success', text: '  11 passed, 0 failed', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'success', text: '✓ Fix applied. Error rate: 342/min → 0/min', delay: 500 },
      { type: 'success', text: '✓ Incident resolved in 47 seconds', delay: 300 },
    ],
  },
  {
    id: 'building',
    mode: 'BUILD',
    icon: '●',
    status: 'running',
    command: 'macrocoder build dashboard --from-spec',
    color: '#f97316',
    description: 'Dashboard generated from a single prompt',
    lines: [
      { type: 'command', text: '$ macrocoder build dashboard --from-spec', delay: 0 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Parsing requirements...', delay: 500 },
      { type: 'output', text: '"Real-time analytics dashboard with user cohort...', delay: 300 },
      { type: 'output', text: 'revenue metrics, and exportable reports"', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '» Scaffolding architecture...', delay: 600 },
      { type: 'info', text: '[Next.js App Router] Setting up routes', delay: 400 },
      { type: 'output', text: '  app/dashboard/page.tsx', delay: 200 },
      { type: 'output', text: '  app/dashboard/analytics/page.tsx', delay: 200 },
      { type: 'output', text: '  app/dashboard/cohorts/page.tsx', delay: 200 },
      { type: 'output', text: '  app/dashboard/revenue/page.tsx', delay: 200 },
      { type: 'output', text: '  app/api/analytics/route.ts', delay: 200 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Generating components (shadcn/ui)...', delay: 600 },
      { type: 'success', text: '✓ RevenueChart — recharts + real-time WebSocket', delay: 400 },
      { type: 'success', text: '✓ CohortTable — sortable, filterable, paginated', delay: 300 },
      { type: 'success', text: '✓ KPICards — revenue, MRR, churn, LTV', delay: 300 },
      { type: 'success', text: '✓ ExportButton — CSV + PDF via jsPDF', delay: 200 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Wiring FastAPI backend...', delay: 500 },
      { type: 'output', text: '  src/api/analytics.py — aggregation queries', delay: 300 },
      { type: 'output', text: '  src/api/cohorts.py — user segmentation', delay: 200 },
      { type: 'output', text: '  src/api/exports.py — report generation', delay: 200 },
      { type: 'success', text: '✓ 3 FastAPI routes, 8 Pydantic models', delay: 400 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Running build...', delay: 500 },
      { type: 'success', text: '✓ TypeScript: 0 errors', delay: 400 },
      { type: 'success', text: '✓ next build completed in 8.2s', delay: 600 },
      { type: 'success', text: '✓ 12 components, 3 API routes, fully typed', delay: 300 },
    ],
  },
  {
    id: 'migrating',
    mode: 'MIGRATE',
    icon: '◇',
    status: 'running',
    command: 'macrocoder migrate --from express --to edge-func...',
    color: '#3b82f6',
    description: 'Express migrated to Edge Functions with no manual patching',
    lines: [
      { type: 'command', text: '$ macrocoder migrate --from express --to edge-functions', delay: 0 },
      { type: 'output', text: '', delay: 300 },
      { type: 'info', text: '[macrocoder] Source: Express.js (Node.js)', delay: 400 },
      { type: 'info', text: '[macrocoder] Target: Next.js API Routes + Edge', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Analyzing route definitions...', delay: 500 },
      { type: 'success', text: '✓ Found 14 route handlers in src/routes/', delay: 600 },
      { type: 'success', text: '✓ Found 8 middleware functions', delay: 300 },
      { type: 'success', text: '✓ Found 3 WebSocket endpoints', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Converting to App Router routes...', delay: 600 },
      { type: 'output', text: '  GET  /api/users          → app/api/users/route.ts', delay: 300 },
      { type: 'output', text: '  POST /api/users          → app/api/users/route.ts', delay: 200 },
      { type: 'output', text: '  GET  /api/users/:id      → app/api/users/[id]/route.ts', delay: 200 },
      { type: 'output', text: '  POST /api/auth/login     → app/api/auth/login/route.ts', delay: 200 },
      { type: 'output', text: '  POST /api/auth/register  → app/api/auth/register/route.ts', delay: 200 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Converting middleware to Edge...', delay: 500 },
      { type: 'success', text: '✓ auth_middleware → middleware.ts (edge runtime)', delay: 400 },
      { type: 'success', text: '✓ rate_limiter → Vercel KV-backed limiter', delay: 300 },
      { type: 'success', text: '✓ cors_handler → next.config.js headers', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Running verification...', delay: 500 },
      { type: 'output', text: '  PASS  14/14 routes respond correctly', delay: 600 },
      { type: 'output', text: '  PASS  8/8 middleware chains preserved', delay: 400 },
      { type: 'success', text: '✓ Migration complete: cold start 1200ms → 18ms', delay: 500 },
    ],
  },
  {
    id: 'securing',
    mode: 'SECURE',
    icon: '□',
    status: 'running',
    command: 'macrocoder audit --fix --strict',
    color: '#ef4444',
    description: 'Security audit and patch pass completed automatically',
    lines: [
      { type: 'command', text: '$ macrocoder audit --fix --strict', delay: 0 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Scanning for vulnerabilities...', delay: 600 },
      { type: 'output', text: '', delay: 300 },
      { type: 'error', text: '✗ CRITICAL: API key exposed in client bundle', delay: 800 },
      { type: 'credential', text: '→ src/lib/api.ts:3 OPENAI_KEY = "sk-proj-8a3f2b1c9e4d7f"', delay: 400 },
      { type: 'error', text: '✗ HIGH: SQL injection in search endpoint', delay: 500 },
      { type: 'output', text: '  → src/api/search.py:28 f"SELECT * WHERE name={q}"', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'warning', text: '⚠ MEDIUM: Missing CSRF on /api/settings', delay: 400 },
      { type: 'warning', text: '⚠ MEDIUM: JWT secret too short (16 chars)', delay: 300 },
      { type: 'warning', text: '⚠ LOW: Verbose error messages in production', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Auto-patching...', delay: 500 },
      { type: 'success', text: '  → Moved OPENAI_KEY to server-only env', delay: 400 },
      { type: 'success', text: '  → Parameterized SQL query', delay: 300 },
      { type: 'success', text: '  → Added CSRF middleware', delay: 300 },
      { type: 'success', text: '  → Generated 64-char JWT secret', delay: 200 },
      { type: 'success', text: '  → Generic error responses enabled', delay: 200 },
      { type: 'output', text: '', delay: 300 },
      { type: 'success', text: '✓ 5 vulnerabilities found, 5 patched', delay: 400 },
      { type: 'success', text: '✓ Security score: 42/100 → 96/100', delay: 300 },
    ],
  },
  {
    id: 'optimizing',
    mode: 'OPTIMIZE',
    icon: '●',
    status: 'running',
    command: 'macrocoder optimize --target lighthouse',
    color: '#22c55e',
    description: 'Lighthouse improved from 34 to 98 in one pass',
    lines: [
      { type: 'command', text: '$ macrocoder optimize --target lighthouse', delay: 0 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Running baseline audit...', delay: 600 },
      { type: 'error', text: '  Performance: 34 ✗', delay: 400 },
      { type: 'error', text: '  Accessibility: 72 ✗', delay: 300 },
      { type: 'error', text: '  Best Practice: 67 ✗', delay: 300 },
      { type: 'error', text: '  SEO: 58 ✗', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Analyzing bottlenecks...', delay: 500 },
      { type: 'info', text: '[Claude Code] LCP blocked by unoptimized images', delay: 400 },
      { type: 'info', text: '[Claude Code] CLS from layout shifts on fonts', delay: 300 },
      { type: 'info', text: '[Claude Code] 1.2MB JS bundle — no code splitting', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Applying fixes...', delay: 500 },
      { type: 'success', text: '✓ Converted 23 images to next/image with AVIF', delay: 400 },
      { type: 'success', text: '✓ Added font-display: swap, preloaded critical fonts', delay: 300 },
      { type: 'success', text: '✓ Dynamic imports: 1.2MB → 340KB initial', delay: 300 },
      { type: 'success', text: '✓ Added aria-labels, alt text, semantic HTML', delay: 300 },
      { type: 'success', text: '✓ Meta tags, structured data, canonical URLs', delay: 200 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Re-running audit...', delay: 500 },
      { type: 'success', text: '  Performance: 98 ✓', delay: 400 },
      { type: 'success', text: '  Accessibility: 100 ✓', delay: 300 },
      { type: 'success', text: '  Best Practice: 100 ✓', delay: 300 },
      { type: 'success', text: '  SEO: 100 ✓', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'success', text: '✓ Lighthouse 34 → 98 overall', delay: 400 },
    ],
  },
]

export const ACTIVITY_LOG = [
  { time: 'now', event: 'Deployed v2.4.1 to production', detail: 'Zero-downtime rolling deploy', status: 'done', sessionId: 'deploying' },
  { time: '2m ago', event: 'Fixed currency mismatch in checkout', detail: 'FastAPI + Stripe webhook sync', status: 'done', sessionId: 'debugging' },
  { time: '5m ago', event: 'Migrated 14 Express routes', detail: 'Next.js Edge Functions', status: 'done', sessionId: 'migrating' },
  { time: '8m ago', event: 'Security audit — 4 issues patched', detail: 'SQL injection + exposed keys', status: 'done', sessionId: 'securing' },
  { time: '12m ago', event: 'Built analytics dashboard (8 files)', detail: 'Next.js + FastAPI + shadcn/ui', status: 'done', sessionId: 'building' },
  { time: '15m ago', event: 'Lighthouse score: 34 → 98', detail: 'Images, fonts, code splitting', status: 'done', sessionId: 'optimizing' },
  { time: '19m ago', event: 'Resolved Stripe webhook failures', detail: 'Idempotency key + retry logic', status: 'done', sessionId: 'debugging' },
  { time: '22m ago', event: 'Added real-time subscriptions', detail: 'WebSocket via FastAPI + React', status: 'done', sessionId: 'building' },
  { time: '26m ago', event: 'Optimized database indices', detail: 'Query performance +340% faster', status: 'done', sessionId: 'optimizing' },
  { time: '31m ago', event: 'Refactored auth middleware', detail: 'JWT + refresh token rotation', status: 'done', sessionId: 'securing' },
  { time: '35m ago', event: 'Fixed N+1 queries in API', detail: 'Batch loading with DataLoader', status: 'done', sessionId: 'debugging' },
  { time: '39m ago', event: 'Deployed hotfix v2.4.0', detail: 'Session timeout issue resolved', status: 'done', sessionId: 'deploying' },
  { time: '44m ago', event: 'Updated dependencies', detail: 'React 19, Next.js 16.1, FastAPI 0.115', status: 'done', sessionId: 'building' },
  { time: '48m ago', event: 'Configured CDN cache rules', detail: 'Smart invalidation with tags', status: 'done', sessionId: 'optimizing' },
  { time: '52m ago', event: 'Added request tracing', detail: 'Full OpenTelemetry integration', status: 'done', sessionId: 'debugging' },
  { time: '57m ago', event: 'Migrated to Vercel KV', detail: 'Rate limiting + session store', status: 'done', sessionId: 'migrating' },
  { time: '1h ago', event: 'Enabled compression', detail: 'Brotli + gzip on all assets', status: 'done', sessionId: 'optimizing' },
  { time: '1h 5m ago', event: 'Patched CORS headers', detail: 'Credential + SameSite policies', status: 'done', sessionId: 'securing' },
  { time: '1h 12m ago', event: 'Built PDF export feature', detail: 'jsPDF + React rendering', status: 'done', sessionId: 'building' },
  { time: '1h 18m ago', event: 'Fixed memory leak in hooks', detail: 'useEffect cleanup handlers', status: 'done', sessionId: 'debugging' },
  { time: '1h 24m ago', event: 'Implemented dark mode toggle', detail: 'CSS-in-JS theme switching', status: 'done', sessionId: 'building' },
  { time: '1h 31m ago', event: 'Upgraded TypeScript 5.3', detail: 'Zero breaking changes', status: 'done', sessionId: 'migrating' },
  { time: '1h 38m ago', event: 'Added metrics dashboard', detail: 'Real-time CPU, memory, latency', status: 'done', sessionId: 'building' },
  { time: '1h 45m ago', event: 'Fixed race condition in cache', detail: 'Atomic operations with Redis WATCH', status: 'done', sessionId: 'debugging' },
  { time: '1h 52m ago', event: 'Deployed v2.3.9 to staging', detail: 'Pre-release testing', status: 'done', sessionId: 'deploying' },
  { time: '1h 59m ago', event: 'Audited package versions', detail: '3 outdated, 0 critical', status: 'done', sessionId: 'securing' },
  { time: '2h 6m ago', event: 'Implemented rate limiting', detail: 'Redis-backed token bucket', status: 'done', sessionId: 'optimizing' },
  { time: '2h 13m ago', event: 'Fixed timezone handling', detail: 'UTC normalization in API', status: 'done', sessionId: 'debugging' },
  { time: '2h 20m ago', event: 'Added webhook retries', detail: 'Exponential backoff + dead letter', status: 'done', sessionId: 'building' },
  { time: '2h 27m ago', event: 'Optimized bundle size', detail: '1.2MB → 340KB main bundle', status: 'done', sessionId: 'optimizing' },
  { time: '2h 34m ago', event: 'Patched SQL injection risk', detail: 'Parameterized all queries', status: 'done', sessionId: 'securing' },
  { time: '2h 41m ago', event: 'Implemented request batching', detail: 'Reduced API calls by 67%', status: 'done', sessionId: 'optimizing' },
  { time: '2h 48m ago', event: 'Fixed CORS preflight', detail: 'Conditional OPTIONS handling', status: 'done', sessionId: 'debugging' },
  { time: '2h 55m ago', event: 'Added error boundaries', detail: 'Graceful React error handling', status: 'done', sessionId: 'building' },
  { time: '3h 2m ago', event: 'Migrated to App Router', detail: '100% next/app adoption', status: 'done', sessionId: 'migrating' },
  { time: '3h 9m ago', event: 'Configured monitoring alerts', detail: 'Slack + PagerDuty integration', status: 'done', sessionId: 'building' },
  { time: '3h 16m ago', event: 'Fixed SSR hydration mismatch', detail: 'useLayoutEffect for DOM reads', status: 'done', sessionId: 'debugging' },
  { time: '3h 23m ago', event: 'Added API versioning', detail: 'v1 → v2 with backward compat', status: 'done', sessionId: 'migrating' },
  { time: '3h 30m ago', event: 'Optimized image pipeline', detail: 'Sharp + on-the-fly resizing', status: 'done', sessionId: 'optimizing' },
  { time: '3h 37m ago', event: 'Patched XSS in user input', detail: 'DOMPurify + CSP headers', status: 'done', sessionId: 'securing' },
  { time: '3h 44m ago', event: 'Built notification center', detail: 'WebSocket + toast + inbox', status: 'done', sessionId: 'building' },
  { time: '3h 51m ago', event: 'Fixed connection pool exhaustion', detail: 'Lifespan-managed pool', status: 'done', sessionId: 'debugging' },
  { time: '3h 58m ago', event: 'Migrated to PostgreSQL 16', detail: 'Zero downtime pg_upgrade', status: 'done', sessionId: 'migrating' },
  { time: '4h 5m ago', event: 'Added GraphQL endpoint', detail: 'Apollo Server + DataLoader', status: 'done', sessionId: 'building' },
  { time: '4h 12m ago', event: 'Optimized cold starts', detail: '800ms → 12ms via pooling', status: 'done', sessionId: 'optimizing' },
  { time: '4h 19m ago', event: 'Rotated all API keys', detail: 'Automated key rotation', status: 'done', sessionId: 'securing' },
  { time: '4h 26m ago', event: 'Fixed race in checkout flow', detail: 'Atomic transactions + locks', status: 'done', sessionId: 'debugging' },
  { time: '4h 33m ago', event: 'Added i18n support', detail: 'next-intl + 5 locales', status: 'done', sessionId: 'building' },
  { time: '4h 40m ago', event: 'Implemented edge caching', detail: 'Stale-while-revalidate strategy', status: 'done', sessionId: 'optimizing' },
  { time: '4h 47m ago', event: 'Fixed memory leak in worker', detail: 'Proper signal handling', status: 'done', sessionId: 'debugging' },
  { time: '4h 54m ago', event: 'Added audit logging', detail: 'Full CRUD event tracking', status: 'done', sessionId: 'securing' },
]

export const JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'j7-1',
    day: 7,
    time: '14:22',
    title: 'Zero-downtime strategy locked in',
    body: "Client's on a managed Postgres with 2 replicas. I can do a blue-green swap — spin the new version alongside the old, run health checks, then flip the load balancer.",
    expandedThought: 'The blue-green approach is optimal here. Since they have 2 replicas, we spin up v2.4 in parallel, verify all health checks pass (API, DB, cache), then atomically flip the load balancer. No downtime. The avatar_url migration is additive so v2.3 continues working if needed for rollback.',
  },
  {
    id: 'j7-2',
    day: 7,
    time: '14:18',
    title: 'Decided against rolling deploy',
    body: "Considered a rolling deploy but the client only has 2 instances. With rolling you'd have v2.3 and v2.4 serving simultaneously — risky with the new DB column.",
    expandedThought: '████████████████ rolling deploy carries compatibility risk ████████████████ With only 2 instances, a gradual rollout means v2.4 and v2.3 handle requests concurrently. If v2.4 tries to read avatar_url before v2.3 writes it, we get nulls. Blue-green eliminates this race.',
  },
  {
    id: 'j6-1',
    day: 6,
    time: '23:41',
    title: 'CDN cache invalidation needs thought',
    body: "The old bundle is cached at 47 edge locations. If I deploy the new API before invalidating the CDN, users will hit the new endpoints with the old client code.",
    expandedThought: '████████████████ deployment sequence ████████████████ The deployment order matters: (1) Deploy API first, (2) Run backwards-compat tests, (3) Purge CDN cache with tag-based invalidation, (4) Deploy new client bundle. Reversing steps 1-3 causes old client → new API version mismatch.',
  },
  {
    id: 'j6-2',
    day: 6,
    time: '21:15',
    title: 'FastAPI dependency injection refactored',
    body: "The get_db() function was creating a new pool per request. Moved to a lifespan handler so the pool is shared. Cold starts went from 800ms to 12ms.",
    expandedThought: '████████████████ connection pooling optimization ████████████████ By moving DB pool initialization to FastAPI lifespan context, we create the pool once at startup instead of 47x per second. Each request now grabs a connection from the shared pool (~1ms) instead of provisioning fresh (150ms+). This was causing cascading 500s during traffic spikes.',
  },
  {
    id: 'j5-1',
    day: 5,
    time: '16:30',
    title: 'n8n webhook integration planned',
    body: "Client wants Slack notifications on deploy. Setting up n8n workflow: GitHub webhook → n8n → Slack. Also adding a secondary path that logs to their internal audit table.",
    expandedThought: '████████████████ n8n webhook architecture ████████████████ GitHub sends push events to n8n HTTP trigger. n8n parses commit message and branch, then routes: if main + "release" tag → Slack notification + audit log. Otherwise silent. Stores deployment metadata (commit, actor, timestamp) in their Postgres for compliance.',
  },
  {
    id: 'j4-1',
    day: 4,
    time: '10:15',
    title: 'Client cache strategy finalized',
    body: "Implemented multi-tier caching: Redis for hot sessions (1h TTL), Vercel KV for distributed cache, browser cache with ETag validation.",
    expandedThought: '████████████████ caching layers ████████████████ Layer 1: Browser (Cache-Control: max-age=3600, ETag). Layer 2: Vercel Edge Network (1h). Layer 3: Redis (sessions, auth tokens, 60m). Layer 4: DB. Misses cascade down. Cache tags on mutations ensure instant invalidation without key rehashing.',
  },
  {
    id: 'j3-1',
    day: 3,
    time: '09:42',
    title: 'Load testing revealed N+1 in analytics',
    body: "During 1k concurrent user simulation, discovered analytics queries were loading user data one-by-one. Refactored to batch queries with SQL ANY().",
    expandedThought: '████████████████ query optimization ████████████████ Original: for each revenue record, SELECT user WHERE id=X. Under load: 47k individual queries. New: SELECT * FROM users WHERE id = ANY(ARRAY[...]) batches 47k into 1. Query time 340ms → 8ms. Confirmed with EXPLAIN ANALYZE before/after.',
  },
  {
    id: 'j2-1',
    day: 2,
    time: '16:20',
    title: 'Stripe webhook idempotency keys',
    body: "Webhook retries were double-charging users. Added idempotency key tracking in a separate table indexed on (webhook_id, timestamp).",
    expandedThought: '████████████████ idempotency implementation ████████████████ Stripe resends webhooks on timeout. Without dedup: same charge_succeeded event processed twice = duplicate invoice. Solution: store idempotency_key on receipt of event, check before processing. Return 200 OK if already processed. Prevents double-charges even with retries.',
  },
  {
    id: 'j1-1',
    day: 1,
    time: '11:00',
    title: 'Project kickoff with client requirements',
    body: "Client needs zero-downtime deploy pipeline, real-time analytics, and audit logging for compliance. Scoped: Next.js frontend, FastAPI backend, n8n workflows.",
    expandedThought: 'Project architecture: Next.js 16 App Router + Server Components for zero-JS pages. FastAPI with async handlers + connection pooling for analytics. PostgreSQL with audit triggers. n8n for webhook orchestration. Target: 99.95% uptime, <50ms p99 latency. Compliance: HIPAA-grade audit logs.',
  },
]

export const LIVE_STATS = {
  uptime: '99.97%',
  responseTime: '12ms',
  deployments: 147,
  filesChanged: 2847,
  testsPassing: '100%',
  migrations: 23,
  securityScore: '96/100',
  activeAgents: 6,
}
