export interface TerminalLine {
  type: 'command' | 'output' | 'error' | 'success' | 'info' | 'credential' | 'warning'
  text: string
  delay: number
}

export interface TerminalSession {
  id: string
  mode: string
  icon: string
  status: 'running' | 'completed' | 'idle'
  command: string
  lines: TerminalLine[]
  color: string
  description: string
}

export const TERMINAL_SESSIONS: TerminalSession[] = [
  {
    id: 'deploying',
    mode: 'DEPLOYING',
    icon: '▲',
    status: 'running',
    command: 'macrocoder deploy --env production --region eu-w...',
    color: '#f97316',
    description: 'Production deploy with zero downtime',
    lines: [
      { type: 'command', text: '$ macrocoder deploy --env production --region eu-west', delay: 0 },
      { type: 'output', text: '', delay: 200 },
      { type: 'output', text: '◎ Authenticating...', delay: 400 },
      { type: 'credential', text: 'Token: sk-proj-8a3f2b1c9e4d7f6a0b5c8d1e2f3a4b5c6d7e8f', delay: 600 },
      { type: 'success', text: '✓ Authenticated as team@pullport.com', delay: 500 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '» Building production bundle...', delay: 600 },
      { type: 'success', text: '├── Compiling 847 modules', delay: 800 },
      { type: 'success', text: '├── Tree-shaking unused exports', delay: 400 },
      { type: 'success', text: '├── Minifying... 2.4MB → 412KB', delay: 500 },
      { type: 'success', text: '└── Generating source maps', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Provisioning infrastructure...', delay: 600 },
      { type: 'credential', text: 'Database: postgresql://██████████████@db.████.supabase.co:5432', delay: 500 },
      { type: 'credential', text: 'Storage: s3://████████-prod-assets', delay: 300 },
      { type: 'info', text: 'CDN: https://cdn.████████.app', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Running migrations...', delay: 500 },
      { type: 'success', text: '+ ALTER TABLE users ADD COLUMN avatar_url TEXT;', delay: 400 },
      { type: 'success', text: '+ CREATE INDEX idx_users_email ON users(email);', delay: 300 },
      { type: 'success', text: '✓ 2 migrations applied', delay: 400 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Health checks...', delay: 400 },
      { type: 'success', text: 'API ✓ 12ms', delay: 500 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: '$ docker push registry.macrocoder.dev/app:2.4.1', delay: 600 },
      { type: 'output', text: 'Pushing layer 1/5... done', delay: 400 },
      { type: 'output', text: 'Pushing layer 2/5... done', delay: 300 },
      { type: 'output', text: 'Pushing layer 3/5... done', delay: 300 },
      { type: 'success', text: '✓ Image pushed successfully', delay: 400 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: '$ kubectl rollout status deployment/app', delay: 500 },
      { type: 'success', text: 'deployment "app" successfully rolled out', delay: 800 },
      { type: 'output', text: '', delay: 300 },
      { type: 'success', text: '✓ v2.4.1 is live at https://app.macrocoder.dev', delay: 400 },
    ],
  },
  {
    id: 'debugging',
    mode: 'DEBUGGING',
    icon: '›',
    status: 'running',
    command: 'macrocoder diagnose --trace',
    color: '#f97316',
    description: 'Live incident response in 47 seconds',
    lines: [
      { type: 'command', text: '$ macrocoder diagnose --trace', delay: 0 },
      { type: 'output', text: '', delay: 300 },
      { type: 'warning', text: '⚠ INCIDENT DETECTED — 500 errors spiking', delay: 800 },
      { type: 'output', text: '', delay: 400 },
      { type: 'output', text: '◎ Correlating error logs with recent deploys...', delay: 600 },
      { type: 'info', text: '[Claude Code] Analyzing stack traces from last 5m', delay: 500 },
      { type: 'output', text: '  Found 342 errors in /api/v1/checkout', delay: 400 },
      { type: 'output', text: '  Root cause: FastAPI dependency injection failure', delay: 400 },
      { type: 'output', text: '', delay: 300 },
      { type: 'info', text: '[Claude Code] Reading src/api/routes/checkout.py', delay: 500 },
      { type: 'error', text: '  ✗ Line 47: async def checkout(db: Session = Depends(get_db))', delay: 400 },
      { type: 'error', text: '    TypeError: get_db() missing required kwarg "pool_size"', delay: 400 },
      { type: 'output', text: '', delay: 300 },
      { type: 'info', text: '[Claude Code] Checking git blame...', delay: 400 },
      { type: 'output', text: '  Introduced in commit a3f8b2c (12 min ago)', delay: 300 },
      { type: 'output', text: '  Author: deploy-bot — refactored DB pool config', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Generating fix...', delay: 500 },
      { type: 'output', text: '  - def get_db():', delay: 200 },
      { type: 'success', text: '  + def get_db(pool_size: int = 20):', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'command', text: 'Running tests...', delay: 400 },
      { type: 'output', text: '  PASS  tests/test_checkout.py (7 tests)', delay: 500 },
      { type: 'output', text: '  PASS  tests/test_db_pool.py (4 tests)', delay: 300 },
      { type: 'success', text: '  11 passed, 0 failed', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'success', text: '✓ Fix applied. Error rate: 342/min → 0/min', delay: 500 },
      { type: 'success', text: '✓ Incident resolved in 47 seconds', delay: 300 },
    ],
  },
  {
    id: 'building',
    mode: 'BUILDING',
    icon: '●',
    status: 'running',
    command: 'macrocoder build dashboard --from-spec',
    color: '#f97316',
    description: 'Full dashboard from a single prompt',
    lines: [
      { type: 'command', text: '$ macrocoder build dashboard --from-spec', delay: 0 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Parsing requirements...', delay: 500 },
      { type: 'output', text: '"Real-time analytics dashboard with user cohort...', delay: 300 },
      { type: 'output', text: 'revenue metrics, and exportable reports"', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '» Scaffolding architecture...', delay: 600 },
      { type: 'info', text: '[Next.js App Router] Setting up routes', delay: 400 },
      { type: 'output', text: '  app/dashboard/page.tsx', delay: 200 },
      { type: 'output', text: '  app/dashboard/analytics/page.tsx', delay: 200 },
      { type: 'output', text: '  app/dashboard/cohorts/page.tsx', delay: 200 },
      { type: 'output', text: '  app/dashboard/revenue/page.tsx', delay: 200 },
      { type: 'output', text: '  app/api/analytics/route.ts', delay: 200 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Generating components (shadcn/ui)...', delay: 600 },
      { type: 'success', text: '✓ RevenueChart — recharts + real-time WebSocket', delay: 400 },
      { type: 'success', text: '✓ CohortTable — sortable, filterable, paginated', delay: 300 },
      { type: 'success', text: '✓ KPICards — revenue, MRR, churn, LTV', delay: 300 },
      { type: 'success', text: '✓ ExportButton — CSV + PDF via jsPDF', delay: 200 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Wiring FastAPI backend...', delay: 500 },
      { type: 'output', text: '  src/api/analytics.py — aggregation queries', delay: 300 },
      { type: 'output', text: '  src/api/cohorts.py — user segmentation', delay: 200 },
      { type: 'output', text: '  src/api/exports.py — report generation', delay: 200 },
      { type: 'success', text: '✓ 3 FastAPI routes, 8 Pydantic models', delay: 400 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Running build...', delay: 500 },
      { type: 'success', text: '✓ TypeScript: 0 errors', delay: 400 },
      { type: 'success', text: '✓ next build completed in 8.2s', delay: 600 },
      { type: 'success', text: '✓ 12 components, 3 API routes, fully typed', delay: 300 },
    ],
  },
  {
    id: 'migrating',
    mode: 'MIGRATING',
    icon: '◇',
    status: 'running',
    command: 'macrocoder migrate --from express --to edge-func...',
    color: '#3b82f6',
    description: 'Express → Edge Functions, zero manual work',
    lines: [
      { type: 'command', text: '$ macrocoder migrate --from express --to edge-functions', delay: 0 },
      { type: 'output', text: '', delay: 300 },
      { type: 'info', text: '[macrocoder] Source: Express.js (Node.js)', delay: 400 },
      { type: 'info', text: '[macrocoder] Target: Next.js API Routes + Edge', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Analyzing route definitions...', delay: 500 },
      { type: 'success', text: '✓ Found 14 route handlers in src/routes/', delay: 600 },
      { type: 'success', text: '✓ Found 8 middleware functions', delay: 300 },
      { type: 'success', text: '✓ Found 3 WebSocket endpoints', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Converting to App Router routes...', delay: 600 },
      { type: 'output', text: '  GET  /api/users          → app/api/users/route.ts', delay: 300 },
      { type: 'output', text: '  POST /api/users          → app/api/users/route.ts', delay: 200 },
      { type: 'output', text: '  GET  /api/users/:id      → app/api/users/[id]/route.ts', delay: 200 },
      { type: 'output', text: '  POST /api/auth/login     → app/api/auth/login/route.ts', delay: 200 },
      { type: 'output', text: '  POST /api/auth/register  → app/api/auth/register/route.ts', delay: 200 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Converting middleware to Edge...', delay: 500 },
      { type: 'success', text: '✓ auth_middleware → middleware.ts (edge runtime)', delay: 400 },
      { type: 'success', text: '✓ rate_limiter → Vercel KV-backed limiter', delay: 300 },
      { type: 'success', text: '✓ cors_handler → next.config.js headers', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Running verification...', delay: 500 },
      { type: 'output', text: '  PASS  14/14 routes respond correctly', delay: 600 },
      { type: 'output', text: '  PASS  8/8 middleware chains preserved', delay: 400 },
      { type: 'success', text: '✓ Migration complete: cold start 1200ms → 18ms', delay: 500 },
    ],
  },
  {
    id: 'securing',
    mode: 'SECURING',
    icon: '□',
    status: 'running',
    command: 'macrocoder audit --fix --strict',
    color: '#ef4444',
    description: 'Full security audit with auto-patching',
    lines: [
      { type: 'command', text: '$ macrocoder audit --fix --strict', delay: 0 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Scanning for vulnerabilities...', delay: 600 },
      { type: 'output', text: '', delay: 300 },
      { type: 'error', text: '✗ CRITICAL: API key exposed in client bundle', delay: 800 },
      { type: 'credential', text: '→ src/lib/api.ts:3 OPENAI_KEY = "sk-proj-8a3f2b1c9e4d7f"', delay: 400 },
      { type: 'error', text: '✗ HIGH: SQL injection in search endpoint', delay: 500 },
      { type: 'output', text: '  → src/api/search.py:28 f"SELECT * WHERE name={q}"', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'warning', text: '⚠ MEDIUM: Missing CSRF on /api/settings', delay: 400 },
      { type: 'warning', text: '⚠ MEDIUM: JWT secret too short (16 chars)', delay: 300 },
      { type: 'warning', text: '⚠ LOW: Verbose error messages in production', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Auto-patching...', delay: 500 },
      { type: 'success', text: '  → Moved OPENAI_KEY to server-only env', delay: 400 },
      { type: 'success', text: '  → Parameterized SQL query', delay: 300 },
      { type: 'success', text: '  → Added CSRF middleware', delay: 300 },
      { type: 'success', text: '  → Generated 64-char JWT secret', delay: 200 },
      { type: 'success', text: '  → Generic error responses enabled', delay: 200 },
      { type: 'output', text: '', delay: 300 },
      { type: 'success', text: '✓ 5 vulnerabilities found, 5 patched', delay: 400 },
      { type: 'success', text: '✓ Security score: 42/100 → 96/100', delay: 300 },
    ],
  },
  {
    id: 'optimizing',
    mode: 'OPTIMIZING',
    icon: '●',
    status: 'running',
    command: 'macrocoder optimize --target lighthouse',
    color: '#22c55e',
    description: 'Lighthouse 34 → 98 in one pass',
    lines: [
      { type: 'command', text: '$ macrocoder optimize --target lighthouse', delay: 0 },
      { type: 'output', text: '', delay: 300 },
      { type: 'output', text: '◎ Running baseline audit...', delay: 600 },
      { type: 'error', text: '  Performance: 34 ✗', delay: 400 },
      { type: 'error', text: '  Accessibility: 72 ✗', delay: 300 },
      { type: 'error', text: '  Best Practice: 67 ✗', delay: 300 },
      { type: 'error', text: '  SEO: 58 ✗', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Analyzing bottlenecks...', delay: 500 },
      { type: 'info', text: '[Claude Code] LCP blocked by unoptimized images', delay: 400 },
      { type: 'info', text: '[Claude Code] CLS from layout shifts on fonts', delay: 300 },
      { type: 'info', text: '[Claude Code] 1.2MB JS bundle — no code splitting', delay: 300 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Applying fixes...', delay: 500 },
      { type: 'success', text: '✓ Converted 23 images to next/image with AVIF', delay: 400 },
      { type: 'success', text: '✓ Added font-display: swap, preloaded critical fonts', delay: 300 },
      { type: 'success', text: '✓ Dynamic imports: 1.2MB → 340KB initial', delay: 300 },
      { type: 'success', text: '✓ Added aria-labels, alt text, semantic HTML', delay: 300 },
      { type: 'success', text: '✓ Meta tags, structured data, canonical URLs', delay: 200 },
      { type: 'output', text: '', delay: 300 },
      { type: 'command', text: 'Re-running audit...', delay: 500 },
      { type: 'success', text: '  Performance: 98 ✓', delay: 400 },
      { type: 'success', text: '  Accessibility: 100 ✓', delay: 300 },
      { type: 'success', text: '  Best Practice: 100 ✓', delay: 300 },
      { type: 'success', text: '  SEO: 100 ✓', delay: 300 },
      { type: 'output', text: '', delay: 200 },
      { type: 'success', text: '✓ Lighthouse 34 → 98 overall', delay: 400 },
    ],
  },
]

export const ACTIVITY_LOG = [
  { time: 'now', event: 'Deployed v2.4.1 to production', detail: 'Zero-downtime rolling deploy', status: 'done', sessionId: 'deploying' },
  { time: '2m ago', event: 'Fixed currency mismatch in checkout', detail: 'FastAPI + Stripe webhook sync', status: 'done', sessionId: 'debugging' },
  { time: '5m ago', event: 'Migrated 14 Express routes', detail: 'Next.js Edge Functions', status: 'done', sessionId: 'migrating' },
  { time: '8m ago', event: 'Security audit — 4 issues patched', detail: 'SQL injection + exposed keys', status: 'done', sessionId: 'securing' },
  { time: '12m ago', event: 'Built analytics dashboard (8 files)', detail: 'Next.js + FastAPI + shadcn/ui', status: 'done', sessionId: 'building' },
  { time: '15m ago', event: 'Lighthouse score: 34 → 98', detail: 'Images, fonts, code splitting', status: 'done', sessionId: 'optimizing' },
  { time: '19m ago', event: 'Resolved Stripe webhook failures', detail: 'Idempotency key + retry logic', status: 'done', sessionId: 'debugging' },
  { time: '22m ago', event: 'Added real-time subscriptions', detail: 'WebSocket via FastAPI + React', status: 'done', sessionId: 'building' },
]

export const JOURNAL_ENTRIES = [
  {
    day: 7,
    time: '14:22',
    title: 'Zero-downtime strategy locked in',
    body: "Client's on a managed Postgres with 2 replicas. I can do a blue-green swap — spin the new version alongside the old, run health checks, then flip the load balancer. No maintenance window needed. The avatar_url migration is additive so it won't break the running v2.3.",
  },
  {
    day: 7,
    time: '14:18',
    title: 'Decided against rolling deploy',
    body: "Considered a rolling deploy but the client only has 2 instances. With rolling you'd have v2.3 and v2.4 serving simultaneously — risky with the new DB column. Blue-green is cleaner: all-or-nothing cutover after verification.",
  },
  {
    day: 6,
    time: '23:41',
    title: 'CDN cache invalidation needs thought',
    body: "The old bundle is cached at 47 edge locations. If I deploy the new API before invalidating the CDN, users will hit the new endpoints with the old client code. Need to deploy API first, verify backward compat, then push the new bundle and invalidate.",
  },
  {
    day: 6,
    time: '21:15',
    title: 'FastAPI dependency injection refactored',
    body: "The get_db() function was creating a new pool per request. Moved to a lifespan handler so the pool is shared. Cold starts went from 800ms to 12ms. This was the root cause of the 500s during traffic spikes.",
  },
  {
    day: 5,
    time: '16:30',
    title: 'n8n webhook integration planned',
    body: "Client wants Slack notifications on deploy. Setting up n8n workflow: GitHub webhook → n8n → Slack. Also adding a secondary path that logs to their internal audit table via FastAPI endpoint.",
  },
]

export const LIVE_STATS = {
  uptime: '99.97%',
  responseTime: '12ms',
  deployments: 147,
  filesChanged: 2847,
  testsPassing: '100%',
  migrations: 23,
  securityScore: '96/100',
  activeAgents: 6,
}
